[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "famnsdk"
version = "1.0.0"
description = "Swagger API client"
readme = "README.md"
requires-python = "\u003e=3.11"
dependencies = ["aiohttp>=3.9.0"]
authors = [{ email = "daniel@kaldheim.org" }]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["py.typed"]

